spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    data-password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
#      show-sql: true
      format-sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


